# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 14 * * *'  # 6:23 AM PST (2:23 PM UTC)
    - cron: '53 14-23/1 * * *'  # Every 30 minutes from 2:53 PM to 11:23 PM UTC

permissions:
  contents: write

jobs:
  if: false # disable workflow
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade google-api-python-client
        python -m pip install --upgrade pip
        pip install flake8 pytest gtfs-realtime-bindings pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics   
    - name: run main.py
      run: |
        python3 ./main.py 3A 1594 csv/rte_3A.csv
    - name: commit changes
      run: |
        git config user.name "Lola Quiroga"
        git config user.email "lolaquiroga25@gmail.com"
        git pull
        git add csv/rte_3A.csv
        git commit -m "update rte_3A.csv from github actions"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}