# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '13 22 * * *'  # 2:13 PM PST (10:13 PM UTC)
    - cron: '28 22-23/1 * * *'  # Every 15 minutes between 10:28 PM and 11:28 PM UTC
    - cron: '00 23 * * *'  # Every hour at the top of the hour from 11:00 PM UTC to 12:00 AM UTC
    - cron: '15 23 * * *'  # 11:15 PM UTC
    - cron: '30 23 * * *'  # 11:30 PM UTC
    - cron: '00 0-7 * * *'  # Every hour on the hour from 12:00 AM UTC to 7:00 AM UTC
    - cron: '15 0-7 * * *'  # Every 15 minutes from 12:15 AM to 7:15 AM UTC
    - cron: '30 0-7 * * *'  # Every 15 minutes from 12:30 AM to 7:30 AM UTC

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade google-api-python-client
        python -m pip install --upgrade pip
        pip install flake8 pytest gtfs-realtime-bindings pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics   
    - name: run main.py
      run: |
        python3 ./main.py 19 1594 csv/rte_19.csv
    - name: commit changes
      run: |
        git config user.name "Lola Quiroga"
        git config user.email "lolaquiroga25@gmail.com"
        git add csv/rte_19.csv
        git commit -m "update rte_19.csv from github actions"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}